include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Unit Test:
  image: docker:latest
  stage: test
  script:
    - docker build -f test.Dockerfile . | tee /dev/tty | tail -n1 | cut -d' ' -f3 | xargs -I{} docker run {}
