include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Unit Test:
  image: docker:latest
  stage: test
  script:
    - docker build -f test.Dockerfile -t unittests .
    - docker run unittests
