include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Unit Test:
  image: quay.io/ebi-ait/ingest-base-images:python_3.10-slim
  stage: test
  before_script:
    - sudo apk update
    - sudo apk add git
    - python -m venv ./venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements-dev.txt
  script:
    - python -m unittest
