include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Unit Test:
  image: quay.io/ebi-ait/ingest-base-images:python_3.10-slim
  stage: test
  script:
    - apt-get update
    - apt-get install -y git
    - pip install --upgrade pip
    - pip install -r requirements-dev.txt
    - python -m unittest
