apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-archiver-service
  namespace: {{ .Values.environment }}-environment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: ingest-archiver
  sessionAffinity: None
  type: NodePort
