# Classese in this module is generated from the ENA experiment and run
# XSDs using the xsdata package.
# The XSDs are in the xsd module. They are downloaded from ENA documentation page:
# https://ena-docs.readthedocs.io/en/latest/submit/reads/programmatic.html
# The instructions to install, use and generate the models using xsdata is here:
# https://xsdata.readthedocs.io/en/latest/

from converter.ena.classes.sra_common import (
    AttributeType,
    BasecallMatchEdge,
    IdentifierType,
    LinkType,
    NameType,
    ObjectType,
    PipelineType,
    PlatformType,
    ProcessingType,
    QualifiedNameType,
    ReadSpecReadClass,
    ReadSpecReadType,
    RefObjectType,
    ReferenceAssemblyType,
    ReferenceSequenceType,
    SequencingDirectivesType,
    SequencingDirectivesTypeSampleDemuxDirective,
    SpotDescriptorType,
    Urltype,
    XrefType,
    Type454Model,
    TypeAbiSolidModel,
    TypeBgiseqmodel,
    TypeCgmodel,
    TypeCapillaryModel,
    TypeDnbSeqModel,
    TypeHelicosModel,
    TypeIlluminaModel,
    TypeIontorrentModel,
    TypeOxfordNanoporeModel,
    TypePacBioModel,
)
from converter.ena.classes.sra_experiment import (
    Experiment,
    ExperimentSet,
    ExperimentSetType,
    ExperimentType,
    LocusLocusName,
    LibraryDescriptorType,
    LibraryType,
    PoolMemberType,
    SampleDescriptorType,
    TypeLibrarySelection,
    TypeLibrarySource,
    TypeLibraryStrategy,
)
from converter.ena.classes.sra_run import (
    FileReadType,
    FileAsciiOffset,
    FileChecksumMethod,
    FileFiletype,
    FileQualityEncoding,
    FileQualityScoringSystem,
    Run,
    RunSet,
    RunSetType,
    RunType,
)

__all__ = [
    "AttributeType",
    "BasecallMatchEdge",
    "IdentifierType",
    "LinkType",
    "NameType",
    "ObjectType",
    "PipelineType",
    "PlatformType",
    "ProcessingType",
    "QualifiedNameType",
    "ReadSpecReadClass",
    "ReadSpecReadType",
    "RefObjectType",
    "ReferenceAssemblyType",
    "ReferenceSequenceType",
    "SequencingDirectivesType",
    "SequencingDirectivesTypeSampleDemuxDirective",
    "SpotDescriptorType",
    "Urltype",
    "XrefType",
    "Type454Model",
    "TypeAbiSolidModel",
    "TypeBgiseqmodel",
    "TypeCgmodel",
    "TypeCapillaryModel",
    "TypeDnbSeqModel",
    "TypeHelicosModel",
    "TypeIlluminaModel",
    "TypeIontorrentModel",
    "TypeOxfordNanoporeModel",
    "TypePacBioModel",
    "Experiment",
    "ExperimentSet",
    "ExperimentSetType",
    "ExperimentType",
    "LocusLocusName",
    "LibraryDescriptorType",
    "LibraryType",
    "PoolMemberType",
    "SampleDescriptorType",
    "TypeLibrarySelection",
    "TypeLibrarySource",
    "TypeLibraryStrategy",
	"FileReadType",
    "FileAsciiOffset",
    "FileChecksumMethod",
    "FileFiletype",
    "FileQualityEncoding",
    "FileQualityScoringSystem",
    "Run",
    "RunSet",
    "RunSetType",
    "RunType",
]
